version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  schoolmanagerweb:
    image: ${DOCKER_REGISTRY-}schoolmanagerweb
    build:
      context: .
      dockerfile: SchoolManagerWeb/SchoolManagerWeb/Dockerfile
    ports:
      - "80:80" # Map HTTP port
      - "443:443" # Map HTTPS port
    networks:
      - app-network
    environment:
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/SchoolManagerWeb.pfx"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=password"
      #- "ConnectionStrings__DefaultConnection=Host=postgres;Database=schoolmanagerdb;Username=yourusername;Password=yourpassword"
    volumes:
      - ./SchoolManagerWeb/SchoolManagerWeb/certs:/https:ro # Mount the cert directory as read-only
      - ./SchoolManagerWeb/SchoolManagerWeb/wwwroot:/app/wwwroot:ro
    depends_on:
      - postgres
    env_file:
      - .env

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: