version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    networks:
      - app-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  schoolmanagerweb:
    image: ${DOCKER_REGISTRY-}schoolmanagerweb
    build:
      context: .
      dockerfile: SchoolManagerWeb/SchoolManagerWeb/Dockerfile
    networks:
      - app-network
    ports:
      - "80:5000"
      - "443:5001"
    volumes:
      - ./SchoolManagerWeb/SchoolManagerWeb/certs:/https:ro # Mount the cert directory as read-only
    depends_on:
      - postgres
    env_file:
      - .env

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
